export default {
  white: "#fff",
  skyblue: "#61C1F4",
  blue: "#009FE2",
  grey: "#DDDDDD",
  darkGrey: "#ABABAB",
  black: "black",
  ligthGreen: "#00BA3E",
  darkGreen: "#0B983A",
  barGrey: "#e0e0e0",
  blueBar: "#232367",
  skyblueBar: "#009FE3",
  greenBar: "#0B983A",
  skyblueCard: "#BBE2FF",
  red: "#BB0000",
  ligthRed: "#DE2B2B",
  redDanger: "red",
  
  // Added from screens
  backgroundColor: "#DDF9FF",
  title: "#333",
  text: "#333",
  switchTrackOff: "#d3d3d3",
  switchTrackOn: "#81b0ff",
  switchThumbOn: "#2196F3",
  switchThumbOff: "#f4f3f4",
  logoutButton: "#e74c3c",
  logoutText: "white",
  shadowColor: "#000",
  cardBackground: "white",
};
